import assert from 'node:assert/strict';
import {createOrbit,bindMouseLook} from '../src/mouse-look.js';
const tests=[];
async function test(name,fn){await fn();tests.push(name)}
function eventTarget(){const listeners={};return {addEventListener(n,fn){(listeners[n]??=[]).push(fn)},fire(n,e={}){for(const fn of listeners[n]||[])fn(e)}}}
function fixture(mode='ok',canMove=()=>true){
 const doc=eventTarget(),canvas=eventTarget(),orbit=createOrbit();let active=true,requests=0,releases=0,states=[];
 canvas.setPointerCapture=()=>{};
 if(mode!=='missing')canvas.requestPointerLock=()=>{requests++;if(mode==='fail')return Promise.reject(new Error('unsupported'));};
 doc.exitPointerLock=()=>{doc.pointerLockElement=null;doc.fire('pointerlockchange')};
 const input=bindMouseLook(canvas,doc,{orbit,canMove,isActive:()=>active,activate:()=>{active=true},onRelease:()=>{releases++;active=false;input.release()},onStatus:s=>states.push(s)});
 const down=(other={})=>canvas.fire('pointerdown',{button:0,pointerType:'mouse',pointerId:1,clientX:100,clientY:100,preventDefault(){},...other});
 const lock=()=>{doc.pointerLockElement=canvas;doc.fire('pointerlockchange')};
 return {doc,canvas,orbit,input,down,lock,setActive:v=>active=v,get:()=>({active,requests,releases,states})};
}
await test('mouse right/left and down/up have correct signs with smooth damping',()=>{const o=createOrbit();o.move(100,100);let v=o.step(.01);assert.ok(v.yaw>0);assert.ok(v.pitch>0);assert.ok(o.get().yaw<o.get().targetYaw);o.recenter(true);o.move(-100,-100);assert.ok(o.step(.1).yaw<0);assert.ok(o.get().pitch<0)});
await test('vertical limits, unlimited horizontal orbit, nonfinite input, shortest recenter',()=>{const o=createOrbit();for(let i=0;i<500;i++){o.move(200,300);o.step(1/60)}assert.equal(o.get().targetPitch,.78);assert.ok(Math.abs(o.get().yaw)<Math.PI*2+1);o.move(NaN,1);assert.ok(Number.isFinite(o.get().yaw));for(let i=0;i<10;i++)o.move(0,-300);assert.equal(o.get().targetPitch,-.28);o.recenter();for(let i=0;i<120;i++)o.step(1/60);assert.ok(Math.abs(Math.sin(o.get().yaw))<1e-8);assert.ok(Math.abs(o.get().pitch)<1e-8);o.recenter(true);assert.deepEqual(o.get(),{yaw:0,pitch:0,targetYaw:0,targetPitch:0})});
await test('only explicit primary mouse click locks; repeated pending and locked clicks are idempotent',()=>{const f=fixture();f.down({pointerType:'touch'});f.down({button:2});assert.equal(f.get().requests,0);f.down();f.down();assert.equal(f.get().requests,1);f.lock();f.down();assert.equal(f.get().requests,1);assert.equal(f.input.get().locked,true);f.doc.fire('mousemove',{movementX:100,movementY:50});assert.ok(f.orbit.get().targetYaw>0)});
await test('unexpected lock loss pauses once; repeated Escape-like loss never resumes',()=>{const f=fixture();f.down();f.lock();f.doc.exitPointerLock();assert.equal(f.get().releases,1);assert.equal(f.get().active,false);f.doc.fire('pointerlockchange');assert.equal(f.get().releases,1);assert.equal(f.input.get().dragging,false);f.doc.fire('mousemove',{movementX:100,movementY:50});assert.equal(f.orbit.get().targetYaw,0);f.down();f.lock();assert.equal(f.get().active,true)});
await test('pause / blur / finish release is intentional and late lock success is discarded',()=>{const f=fixture();f.down();f.lock();f.setActive(false);f.input.release();assert.equal(f.get().releases,0);assert.equal(f.input.get().locked,false);f.down();f.setActive(false);f.input.release();f.lock();assert.equal(f.doc.pointerLockElement,null);assert.equal(f.input.get().locked,false);assert.equal(f.get().releases,0)});
await test('rejected lock request falls back to left-drag and clears on cancel/release',async()=>{const f=fixture('fail');f.down();await Promise.resolve();assert.equal(f.input.get().fallback,true);f.down();f.canvas.fire('pointermove',{pointerId:1,clientX:160,clientY:120});assert.ok(f.orbit.get().targetYaw>0);f.canvas.fire('pointercancel',{pointerId:1});assert.equal(f.input.get().dragging,false);const yaw=f.orbit.get().targetYaw;f.canvas.fire('pointermove',{pointerId:1,clientX:200,clientY:120});assert.equal(f.orbit.get().targetYaw,yaw);f.down();f.input.release();assert.equal(f.input.get().dragging,false)});
await test('left-drag stops on its own button release even with another button held',()=>{const f=fixture('missing');f.down();f.canvas.fire('pointermove',{pointerId:1,pointerType:'mouse',buttons:2,clientX:200,clientY:120});assert.equal(f.input.get().dragging,false);f.canvas.fire('pointermove',{pointerId:1,clientX:200,clientY:120});assert.equal(f.orbit.get().targetYaw,0)});
await test('rear-view movement never accumulates into a drag orbit jump',()=>{let allowed=true;const f=fixture('missing',()=>allowed);f.down();allowed=false;f.canvas.fire('pointermove',{pointerId:1,buttons:3,clientX:300,clientY:100});assert.equal(f.orbit.get().targetYaw,0);allowed=true;f.canvas.fire('pointermove',{pointerId:1,buttons:1,clientX:300,clientY:100});assert.equal(f.orbit.get().targetYaw,0);f.canvas.fire('pointermove',{pointerId:1,buttons:1,clientX:310,clientY:100});assert.ok(Math.abs(f.orbit.get().targetYaw-.03)<1e-9)});
await test('browsers without pointer lock support retain drag-look and ignore touch',()=>{const f=fixture('missing');f.down({pointerType:'touch'});assert.equal(f.input.get().dragging,false);f.down();assert.equal(f.input.get().dragging,true);f.canvas.fire('pointerup',{pointerId:1});assert.equal(f.input.get().dragging,false)});
console.log(JSON.stringify({status:'passed',suite:'mouse orbit and pointer lifecycle',tests},null,2));
