import test from 'node:test';import assert from 'node:assert/strict';
import {newWaterRace,advanceWaterRace,advanceWaterCheckpoints,waterStandings,resetWaterPickups,useWaterItem,WATER_CHECKPOINTS,WATER_LAPS} from '../src/water-race';
import {WATER_RACE_LENGTH} from '../src/waterpark-design';
import type {RacingPickup} from '../src/npc-tactics';
const input={throttle:true,brake:false,steer:0};
function boxes():RacingPickup[]{return Array.from({length:24},(_,i)=>({d:45+Math.floor(i/3)*75,lateral:(i%3-1)*4,display:'boost',cool:0,mesh:{enabled:true},models:{boost:{enabled:true},shield:{enabled:false},pulse:{enabled:false},mystery:{enabled:false}}}));}
function run(hz:number){const race=newWaterRace('whale'),pickups=boxes();resetWaterPickups(race,pickups);for(let i=0;i<hz*180&&!race.finished;i++)advanceWaterRace(race,input,1/hz,pickups);return race;}
test('six unique racers all finish three complete laps with real results and deterministic replay',()=>{const race=run(60);assert.ok(race.finished);assert.equal(new Set(race.racers.map(r=>r.id)).size,6);for(const r of race.racers){assert.equal(r.checkpoint,24);assert.equal(r.total,WATER_RACE_LENGTH*3);assert.ok(r.finishTime!>70);assert.equal(r.speed,0);}assert.deepEqual(run(60),race);assert.ok(race.racers.slice(1).some(r=>r.pickups>0&&r.uses>0));assert.ok(race.racers.every(r=>r.uses<=r.pickups));const sorted=waterStandings(race);assert.ok(sorted.every((r,i)=>i===0||r.finishTime!>=sorted[i-1].finishTime!));});
test('race finish times and rank are identical at 30, 60 and 120 Hz',()=>{const a=run(30),b=run(60),c=run(120);assert.deepEqual(a.racers,b.racers);assert.deepEqual(a.racers,c.racers);});
test('countdown and effects use simulation time; invalid deltas and finished frames do nothing',()=>{const r=newWaterRace('glm');advanceWaterRace(r,input,2.5);assert.equal(r.elapsed,0);assert.equal(r.racers[0].total,0);advanceWaterRace(r,input,.6);assert.ok(Math.abs(r.elapsed-.1)<.009);const snapshot=structuredClone(r);advanceWaterRace(r,input,NaN);advanceWaterRace(r,input,-1);advanceWaterRace(r,input,1e12);assert.deepEqual(r,snapshot);const done=run(60),saved=structuredClone(done);advanceWaterRace(done,input,3);assert.deepEqual(done,saved);});
test('reverse, seam oscillation and checkpoint skips cannot earn laps',()=>{const r={checkpoint:0},gap=WATER_RACE_LENGTH/WATER_CHECKPOINTS;advanceWaterCheckpoints(r,0,WATER_RACE_LENGTH);assert.equal(r.checkpoint,0);advanceWaterCheckpoints(r,gap+1,gap-1);assert.equal(r.checkpoint,0);advanceWaterCheckpoints(r,gap-1,gap+1);assert.equal(r.checkpoint,1);advanceWaterCheckpoints(r,gap+1,gap-1);advanceWaterCheckpoints(r,gap-1,gap+1);assert.equal(r.checkpoint,1);for(let gate=2;gate<=WATER_CHECKPOINTS*WATER_LAPS;gate++)advanceWaterCheckpoints(r,gate*gap-1,gate*gap+1);assert.equal(r.checkpoint,24);});
test('inventory starts empty and player cannot create items during countdown or after finish',()=>{const race=newWaterRace('gpt');for(const r of race.racers)assert.equal(r.held,null);race.racers[0].held='boost';useWaterItem(race,race.racers[0]);assert.equal(race.racers[0].held,'boost');advanceWaterRace(race,input,3.1);useWaterItem(race,race.racers[0]);assert.equal(race.racers[0].held,null);assert.ok(race.racers[0].boost>0);});
test('contact impulses are local, shield-aware and cannot use a finisher as an obstacle',()=>{const r=newWaterRace('whale');r.countdown=0;const [a,b]=r.racers;a.total=b.total=20;a.lateral=b.lateral=0;a.motion={...a.motion,distance:20,lane:0,speed:10};b.motion={...b.motion,distance:20,lane:0,speed:10};a.shield=2;advanceWaterRace(r,input,1/120);assert.ok(a.bump>0&&b.bump>0);assert.equal(a.motion.lateralSpeed,0);assert.ok(Math.abs(b.motion.lateralSpeed)>1);const finished=newWaterRace('whale');finished.countdown=0;finished.racers[1].finishTime=1;finished.racers[1].total=finished.racers[0].total;finished.racers[1].lateral=finished.racers[0].lateral;advanceWaterRace(finished,input,1/120);assert.equal(finished.racers[0].bump,0);});
test('player finish freezes controls while remaining riders keep truthful pending times',()=>{const race=newWaterRace('gpt');race.countdown=0;const player=race.racers[0];player.checkpoint=23;player.total=WATER_RACE_LENGTH*3-.03;player.motion={...player.motion,distance:player.total,speed:20};advanceWaterRace(race,input,1/60);assert.ok(player.finishTime!==null);assert.ok(player.finishTime!<1/60);assert.equal(race.finished,false);assert.ok(race.racers.slice(1).every(r=>r.finishTime===null));const finished=structuredClone(player.motion);advanceWaterRace(race,{...input,steer:1},1);assert.deepEqual(player.motion,finished);assert.equal(waterStandings(race)[0].id,player.id);});
test('all six profiles drive actual player and NPC acceleration, caps and steering equally',async()=>{const {CHARACTER_PROFILES,characterTuning}=await import('../src/character-profiles');const {WATER_HANDLING}=await import('../src/waterpark-motion');const dt=1/120;
 for(const profile of CHARACTER_PROFILES){
  const race=newWaterRace(profile.id);race.countdown=0;for(const [i,r] of race.racers.entries()){r.total=i*40;r.motion.distance=r.total;}
  advanceWaterRace(race,{...input,steer:1},dt);
  for(const racer of race.racers){const tuning=characterTuning(racer.id,'waterpark');assert.ok(Math.abs(racer.speed-tuning.acceleration*dt*Math.exp(-WATER_HANDLING.drag*dt))<1e-10,`${racer.id} acceleration as ${racer===race.racers[0]?'player':'NPC'}`);}
  const player=race.racers[0],tuning=characterTuning(profile.id,'waterpark');const expectedLateral=tuning.steering*Math.min(1,player.speed/6)*dt*Math.exp(-WATER_HANDLING.lateralDrag*dt);assert.ok(Math.abs(player.motion.lateralSpeed-expectedLateral)<1e-10,`${profile.id} steering`);
  for(const racer of race.racers){racer.motion.speed=1000;racer.boost=racer.slow=0;}
  advanceWaterRace(race,input,dt);for(const racer of race.racers)assert.equal(racer.speed,characterTuning(racer.id,'waterpark').maxSpeed,`${racer.id} cap`);
 }
});
