import {CHARACTER_PROFILES,resolveCharacter,characterTuning} from './character-profiles';
import {MAP_PROFILES,resolveMap,type MapId} from './map-profiles';
import {readGameSettings,saveGameSettings,type Quality} from './game-settings';
import {parseMenuState,menuQuery,raceEntry,type MenuScreen} from './menu-state';
const root=document.getElementById('menu')!;
let state=parseMenuState(location.search),settings=readGameSettings();
const art=(water=false)=>`<svg class="route-art" viewBox="0 0 600 400" aria-hidden="true"><defs><linearGradient id="road-${water?'water':'coast'}" x2="1" y2="1"><stop stop-color="${water?'#70e1ee':'#d2e47d'}"/><stop offset="1" stop-color="${water?'#5f94cd':'#ebaf72'}"/></linearGradient></defs><ellipse cx="314" cy="300" rx="218" ry="65" fill="#081d24" opacity=".3"/><path class="route-shadow" d="M115 233 C42 161 159 67 256 109 S393 105 430 153 S569 242 451 289 S194 312 115 233Z"/><path class="route-line" style="stroke:url(#road-${water?'water':'coast'})" d="M115 233 C42 161 159 67 256 109 S393 105 430 153 S569 242 451 289 S194 312 115 233Z"/><path class="route-dash" d="M115 233 C42 161 159 67 256 109 S393 105 430 153 S569 242 451 289 S194 312 115 233Z"/><circle cx="257" cy="194" r="54" fill="${water?'#7ecee3':'#f1c37b'}" opacity=".75"/><path d="M223 205q34-35 68 0M238 221q20-22 39 0" fill="none" stroke="#fff" stroke-width="5" opacity=".6"/><g transform="translate(398 257) rotate(-25)"><rect x="-22" y="-12" width="44" height="24" rx="10" fill="#d5ff60"/><rect x="-10" y="-10" width="15" height="20" rx="5" fill="#24474b"/><path d="M-18-17v8m0 17v8m31-33v8m0 17v8" stroke="#0e252e" stroke-width="6"/></g></svg>`;
function navigate(screen:MenuScreen,updates:Partial<typeof state>={}){state={...state,...updates,screen};history.pushState(null,'',`./index.html${menuQuery(state)}`);render();root.focus({preventScroll:true});window.scrollTo({top:0});}
function top(title:string,sub:string,back:MenuScreen='main'){return `<div class="section-top"><button class="back text-button" data-screen="${back}">← 返回${back==='maps'?'地图选择':'主菜单'}</button><button class="text-button" data-screen="settings">画面设置 ↗</button></div><div class="section-heading"><p class="eyebrow">FREE PLAY / 自由模式</p><h1>${title}</h1><p>${sub}</p></div>`;}
function render(){
 document.title=`${({main:'主菜单',maps:'选择地图',characters:'选择角色',settings:'游戏设置',exit:'休息一下'})[state.screen]} · AI Friends Kart`;
 root.className=`screen-${state.screen}`;
 if(state.screen==='main')root.innerHTML=`<section class="hero"><div class="hero-copy"><p class="eyebrow">SIX FRIENDS. ONE FINISH LINE.</p><h1>一起出发，<br><em>快乐竞速。</em></h1><p class="hero-lede">海岸公路，或是晴空水道？<br>挑选你的伙伴，把下一圈交给风。</p><div class="main-actions"><button class="primary main-action" data-screen="maps"><span><small>FREE PLAY</small>自由模式</span><span>↗</span></button><button class="secondary main-action" disabled aria-describedby="story-note"><span><small>STORY MODE</small>故事模式</span><span class="badge">开发中</span></button><p id="story-note" class="fine-print">故事模式尚未开放，先来一场自由竞速吧</p><div class="utility-actions"><button data-screen="settings">游戏设置</button><button data-screen="exit">退出游戏</button></div></div></div><div class="hero-art">${art()}<div class="art-caption"><span>01 / 02　SUNSET COAST</span><strong>下一站，发车线</strong><small>赛道风格示意 · 实际游戏为 3D 场景</small></div><div class="floating-chip">6 位角色 <span>×</span> 2 张地图</div></div></section>`;
 if(state.screen==='maps')root.innerHTML=top('今天，去哪里？','选择一张地图，再选择你和对手共同使用的六位伙伴。')+`<div class="map-grid">${Object.values(MAP_PROFILES).map((m,i)=>`<button class="map-card ${m.id}" data-map="${m.id}"><div class="map-visual">${art(m.id==='waterpark')}<span class="map-number">0${i+1}</span><span class="vehicle-badge">${m.vehicle==='kart'?'卡丁车':'鲸鱼坐骑'}</span></div><div class="map-copy"><span class="eyebrow">${m.tag}</span><h2>${m.label}<span>↗</span></h2><p>${m.detail}</p><div class="card-foot">${m.description}<span>选择地图 →</span></div></div></button>`).join('')}</div><p class="bottom-note">两张地图共用角色模型与属性差异；载具、赛道和驾驶手感各有特色</p>`;
 if(state.screen==='characters'){
 const map=resolveMap(state.map),selected=resolveCharacter(state.driver),t=characterTuning(selected.id,state.map);
 const stats=[['加速能力',selected.acceleration,t.acceleration,'m/s²'],['最高速度',selected.topSpeed,t.maxSpeed,'m/s'],[state.map==='waterpark'?'转向加速度':'转向横移能力',selected.steering,t.steering,state.map==='waterpark'?'m/s²':'m/s']];
 root.innerHTML=top('选一位出发伙伴',`${map.label} · ${map.vehicle==='kart'?'卡丁车':'鲸鱼坐骑'}　/　六名选手，同场竞速`,'maps')+`<div class="character-layout"><div class="character-grid" role="group" aria-label="选择参赛角色">${CHARACTER_PROFILES.map(c=>`<button class="character-card" style="--character:${c.color}" data-driver="${c.id}" aria-pressed="${c.id===selected.id}"><span class="character-symbol" aria-hidden="true">${c.symbol}</span><span class="character-name">${c.label}</span><span class="character-role">${c.nickname}</span><span class="selected-mark" aria-hidden="true">${c.id===selected.id?'✓':'+'}</span></button>`).join('')}<p class="roster-note">标记为角色识别符号。进入赛道后加载完整 3D 角色模型。</p></div><aside class="profile-panel" aria-label="已选角色属性" style="--character:${selected.color}"><p class="eyebrow">YOUR DRIVER / 已选伙伴</p><h2>${selected.label}</h2><p class="profile-role">${selected.nickname}</p><p class="profile-description">${selected.description}</p><div class="stats">${stats.map(([label,mult,value,unit])=>`<div class="stat"><div><span>${label}</span><strong>${Number(value).toFixed(2)} <small>${unit}</small></strong></div><meter min="0.85" max="1.15" value="${mult}" aria-label="${label}，标准值的 ${Math.round(Number(mult)*100)}%"></meter><span class="stat-percent">标准值 × ${Number(mult).toFixed(2)}</span></div>`).join('')}</div><p class="stats-note">${state.map==='waterpark'?'加速是阻力修正前的推进加速度；极速是基础速度上限。转向是横向加速度，实际横移受惯性与阻尼影响。':'基础参数，不含道具、漂移与地形修正。转向是正常极速下的横移速度，不是转弯角度。'}玩家与对手使用相同角色系数。</p><a class="primary start-race" id="start-race" href="${raceEntry(state.map,selected.id)}"><span>开始比赛</span><span>→</span></a><p class="fine-print">首次进入需要下载 3D 资源，请稍候</p></aside></div>`;
 }
 if(state.screen==='settings')root.innerHTML=`<div class="section-top"><button class="text-button" data-screen="${state.returnTo}">← 返回${state.returnTo==='characters'?'角色选择':state.returnTo==='maps'?'地图选择':'主菜单'}</button></div><div class="section-heading"><p class="eyebrow">MAKE IT YOURS</p><h1>游戏设置</h1><p>应用于接下来进入的赛道，自动保存在此浏览器</p></div><section class="settings-panel"><fieldset><legend>画面质量</legend><p>流畅档关闭阴影并降低渲染分辨率；精细档提高阴影清晰度</p><div class="quality-options">${[['low','流畅','低分辨率 · 无阴影'],['balanced','均衡','标准分辨率 · 标准阴影'],['high','精细','标准分辨率 · 精细阴影']].map(([q,name,desc])=>`<label><input type="radio" name="quality" value="${q}" ${settings.quality===q?'checked':''}><span><strong>${name}</strong><small>${desc}</small></span></label>`).join('')}</div></fieldset><div class="setting-row"><div><label for="refraction">水面折射</label><p>水上乐园的透水折射效果；关闭可减轻渲染负担</p></div><input type="checkbox" id="refraction" ${settings.refraction?'checked':''}></div><div class="setting-row muted-row"><div><strong>背景音乐</strong><p>暂未加入背景音乐，后续版本再见</p></div><span class="badge">待加入</span></div><section class="controls-guide" aria-label="操作说明"><h2>操作说明</h2><h3>日落海岸 · 卡丁车</h3><p>W / ↑ 油门 · S / ↓ 刹车与倒车<br>A / D 或 ← / → 转向 · 空格 刹车<br>Shift 漂移 · E 使用道具 · Z 切换视角<br>单击赛道后移动鼠标环顾 · Q 视角回正<br>Esc / P 暂停或继续</p><h3>晴空水上乐园 · 鲸鱼坐骑</h3><p>W / ↑ 油门 · S / ↓ 减速<br>A / D 或 ← / → 转向 · E 使用道具<br>Esc / P 暂停或继续 · R 重新比赛</p><p>触屏：使用赛道画面中的转向、油门、刹车及道具按钮。菜单可用 Tab 切换焦点、Enter 确认、Esc 返回。</p></section><p class="settings-status" id="settings-status" role="status" aria-live="polite">设置已载入</p><button class="text-button" id="reset-settings">恢复默认设置</button></section>`;
 if(state.screen==='exit')root.innerHTML=`<section class="exit-panel"><p class="eyebrow">SEE YOU AT THE START LINE</p><div class="exit-symbol" aria-hidden="true">☀</div><h1>休息一下，<br>随时再出发。</h1><p>已返回休息页面，没有比赛在后台运行。<br>你可以关闭此标签页退出游戏。</p><button class="primary" data-screen="main">返回主菜单 →</button></section>`;
 bind();
}
function bind(){
 root.querySelectorAll<HTMLElement>('[data-screen]').forEach(button=>button.addEventListener('click',()=>{const target=button.dataset.screen as MenuScreen;navigate(target,target==='settings'?{returnTo:state.screen==='maps'||state.screen==='characters'?state.screen:'main'}:{});}));
 root.querySelectorAll<HTMLElement>('[data-map]').forEach(button=>button.addEventListener('click',()=>navigate('characters',{map:button.dataset.map as MapId,driver:'whale'})));
 root.querySelectorAll<HTMLElement>('[data-driver]').forEach(button=>button.addEventListener('click',()=>{state.driver=resolveCharacter(button.dataset.driver).id;history.replaceState(null,'',`./index.html${menuQuery(state)}`);render();root.querySelector<HTMLElement>(`[data-driver="${state.driver}"]`)?.focus({preventScroll:true});}));
 const status=(saved:boolean)=>{const node=document.getElementById('settings-status');if(node)node.textContent=saved?'已保存，下次进入赛道时生效':'此浏览器无法保存设置；重新进入赛道将使用默认值';};
 root.querySelectorAll<HTMLInputElement>('[name="quality"]').forEach(input=>input.addEventListener('change',()=>{settings={...settings,quality:input.value as Quality};status(saveGameSettings(settings));}));
 root.querySelector<HTMLInputElement>('#refraction')?.addEventListener('change',event=>{settings={...settings,refraction:(event.target as HTMLInputElement).checked};status(saveGameSettings(settings));});
 root.querySelector('#reset-settings')?.addEventListener('click',()=>{settings={version:1,quality:'balanced',refraction:true};const saved=saveGameSettings(settings);render();status(saved);root.querySelector<HTMLElement>('#reset-settings')?.focus();});
}
window.addEventListener('popstate',()=>{state=parseMenuState(location.search);settings=readGameSettings();render();root.focus({preventScroll:true});});
window.addEventListener('keydown',event=>{if(event.key!=='Escape')return;if(state.screen==='characters')navigate('maps');else if(state.screen==='settings')navigate(state.returnTo);else if(state.screen!=='main')navigate('main');});
render();
