import { npcLine, type NpcSkill } from './npc-difficulty';
import type { ItemKind } from './item-models';
import { claimPickup, type PickupState } from './item-pickups';

/** Shared race rules: no inventory is generated by the AI. All clocks use race dt. */
export const RULES = Object.freeze({ boost: 3.3, shield: 6, slow: 3, slowFactor: .55, boostFactor: 1.34, pulseRange: 120, lateralSpeed: 4, reaction: .65, cooldown: 1.2 });
export interface Combatant {
  id: string; total: number; lateral: number; speed: number;
  held: ItemKind | null; boost: number; shield: number; slow: number;
}
export interface Brain { bump: number; decisionIn: number; reaction: number; cooldown: number; targetLane: number; pulseFlash: number; pickups: number; uses: number }
export interface RacingPickup extends PickupState { d: number; lateral: number; dynamic?: boolean }
export const newBrain = (phase: number, lane: number): Brain => ({ bump: 0, decisionIn: phase * .047, reaction: 0, cooldown: 0, targetLane: lane, pulseFlash: 0, pickups: 0, uses: 0 });
const clamp = (n: number, low: number, high: number) => Math.max(low, Math.min(high, n));
export const forwardGap = (from: number, to: number, length: number) => { const gap = (to - from) % length; return gap < 0 ? gap + length : gap; };
export const nearbyGap = (from: number, to: number, length: number) => ((to - from + length / 2) % length + length) % length - length / 2;
export const racingSpeed = (r: Combatant, max: number) => clamp(r.speed, 0, max) * (r.boost > 0 ? RULES.boostFactor : 1) * (r.slow > 0 ? RULES.slowFactor : 1);
export function tickEffects(r: Combatant, dt: number) {
  for (const key of ['boost', 'shield', 'slow'] as const) r[key] = Math.max(0, r[key] - Math.max(0, dt));
}
export function tickBrain(b: Brain, dt: number) {
  for (const key of ['bump', 'decisionIn', 'reaction', 'cooldown', 'pulseFlash'] as const) b[key] = Math.max(0, b[key] - Math.max(0, dt));
}
export function pulseTarget(actor: Combatant, racers: readonly Combatant[], length: number) {
  return racers.filter(r => r.id !== actor.id).map(r => ({ r, gap: forwardGap(actor.total, r.total, length) }))
    .filter(t => t.gap > .1 + 1e-8 && t.gap < RULES.pulseRange - 1e-8).sort((a, b) => a.gap - b.gap || a.r.id.localeCompare(b.r.id))[0]?.r;
}
/** A shield stops the nearest incoming pulse; it never skips through to a rear target. */
export function activateItem(actor: Combatant, racers: readonly Combatant[], length: number) {
  const item = actor.held;
  if (!item) return null;
  actor.held = null;
  let target: Combatant | undefined, blocked = false;
  if (item === 'boost') actor.boost = Math.max(actor.boost, RULES.boost);
  else if (item === 'shield') actor.shield = Math.max(actor.shield, RULES.shield);
  else {
    target = pulseTarget(actor, racers, length);
    if (target) { blocked = target.shield > 0; if (!blocked) target.slow = Math.max(target.slow, RULES.slow); }
    else actor.boost = Math.max(actor.boost, 1.9); // Preserve the player's no-target fallback.
  }
  return { item, target, blocked };
}
export function chooseItem(actor: Combatant & Brain, racers: readonly Combatant[], length: number, bend: number, skill?: NpcSkill): ItemKind | null {
  if (!actor.held || actor.reaction > 0 || actor.cooldown > 0) return null;
  const neighbors = racers.filter(r => r.id !== actor.id).map(r => ({ r, gap: nearbyGap(actor.total, r.total, length) }));
  if (actor.held === 'shield') {
    const threatened = neighbors.some(({ r, gap }) => (Math.abs(gap) < 10 && Math.abs(r.lateral - actor.lateral) < 2.3 && (Math.abs(gap) < 4 || (gap > 0 ? actor.speed > r.speed : r.speed > actor.speed))) || (gap < -.1 && gap > -60 && r.held === 'pulse'));
    return actor.shield <= 0 && threatened ? 'shield' : null;
  }
  if (actor.held === 'pulse') { const target = pulseTarget(actor, racers, length); return target && target.shield <= 0 && target.slow < .5 ? 'pulse' : null; }
  const blocked = neighbors.some(({ r, gap }) => gap > 0 && gap < 24 && Math.abs(r.lateral - actor.lateral) < 2.3);
  return actor.boost <= 0 && actor.slow <= 0 && actor.speed > 12 && Math.abs(actor.lateral) < 5.3 && Math.abs(bend) < (skill?.boostBend ?? .3) && !blocked ? 'boost' : null;
}
/** Local, bounded lane planning. Does not inspect pickups beyond 48 m or reverse. */
export function planLane(actor: Combatant, racers: readonly Combatant[], boxes: readonly RacingPickup[], length: number, phase: number, bend: number, skill?: NpcSkill) {
  let lane = skill ? npcLine(actor.total, phase, bend, skill) : Math.sin(actor.total / 90 + phase) * 2.6;
  if (!actor.held && Math.abs(bend) < .5) {
    const candidates = boxes.filter(b => b.cool <= 0 && b.mesh.enabled).map(box => ({ box, gap: forwardGap(actor.total, box.d, length) }))
      .filter(({ box, gap }) => gap >= 2 && gap <= (skill?.pickupLookAhead ?? 48) && Math.abs(box.lateral) <= 5.2 && Math.abs(box.lateral - actor.lateral) <= RULES.lateralSpeed * gap / Math.max(12, actor.speed * (actor.boost > 0 ? RULES.boostFactor : 1)) + .65)
      .filter(({ box, gap }) => !racers.some(r => r.id !== actor.id && Math.abs(nearbyGap(actor.total, r.total, length)) < Math.min(gap, 12) && Math.abs(r.lateral - box.lateral) < 1.8))
      .sort((a, b) => (a.gap + Math.abs(a.box.lateral - actor.lateral) * 4) - (b.gap + Math.abs(b.box.lateral - actor.lateral) * 4));
    if (candidates[0]) lane = candidates[0].box.lateral;
  }
  const traffic = racers.filter(r => r.id !== actor.id && Math.abs(r.lateral - lane) < 1.9)
    .map(r => ({ r, gap: nearbyGap(actor.total, r.total, length) })).filter(t => t.gap > -2 && t.gap < 12).sort((a, b) => a.gap - b.gap)[0];
  if (traffic) lane = traffic.r.lateral + (actor.lateral >= traffic.r.lateral ? 2.4 : -2.4);
  return clamp(lane, -5.2, 5.2);
}
export function moveLane(lane: number, target: number, dt: number) {
  return clamp(lane + clamp(target - lane, -RULES.lateralSpeed * Math.max(0, dt), RULES.lateralSpeed * Math.max(0, dt)), -5.2, 5.2);
}
export interface PickupRacer { actor: Combatant; previous: number; previousLane: number; onPickup?: (kind: ItemKind) => void }
/** Swept collision, ordered by time of contact, prevents tunnelling and player-first bias.
 * Exact ties use stable racer IDs rather than frame iteration order. */
export function collectPickups(racers: readonly PickupRacer[], boxes: readonly RacingPickup[], length: number, rng = Math.random) {
  const claims: { racer: PickupRacer; box: RacingPickup; time: number; index: number }[] = [];
  boxes.forEach((box, index) => {
    if (box.cool > 0 || !box.mesh.enabled) return;
    for (const racer of racers) {
      if (racer.actor.held) continue;
      const travel = racer.actor.total - racer.previous;
      // Cover the start's nearest copy and the next crossed lap seam in either direction.
      const base = Math.round((racer.previous - box.d) / length);
      for (let lap = base - 1; lap <= base + 1; lap++) {
        const center = box.d + lap * length;
        let enter = 0, leave = 1;
        for (const [start, delta, low, high] of [[racer.previous, travel, center - 1.8, center + 1.8], [racer.previousLane, racer.actor.lateral - racer.previousLane, box.lateral - 1.25, box.lateral + 1.25]]) {
          if (Math.abs(delta) < 1e-9) { if (start < low || start > high) { enter = 2; break; } }
          else { const a = (low - start) / delta, b = (high - start) / delta; enter = Math.max(enter, Math.min(a, b)); leave = Math.min(leave, Math.max(a, b)); }
        }
        if (enter <= leave && enter <= 1 && leave >= 0) { claims.push({ racer, box, time: enter, index }); break; }
      }
    }
  });
  claims.sort((a, b) => a.time - b.time || a.racer.actor.id.localeCompare(b.racer.actor.id) || a.index - b.index);
  for (const { racer, box } of claims) {
    const reward = claimPickup(box, racer.actor.held !== null, rng);
    if (reward) { racer.actor.held = reward; racer.onPickup?.(reward); }
  }
}
